### ISSUE TITLE
Seminar today - and next week too!

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/WWU-seminar-2018#18]
We'll be working on Lab 5, a short one on data visualization.

Next week we'll be talking about fitting models to data, a critical tool in a scientist's arsenal!

(attn: @nataliegmoore @choudrs @ballanr @MeganMcAndie @karlaburch @erinleighh @amandarudolph @mscogs @ZacheryLaycock @frizzek @barberdegraaff @gibbslena @JMollerup)

**Comment by nataliegmoore** [comment]
Sorry I was unable to make it today! I will do the lab at home.

Natalie Moore

From: James Davenport
Sent: Wednesday, May 9, 2018 4:17 PM
To: jradavenport/WWU-seminar-2018
Cc: Natalie Moore; Mention
Subject: [jradavenport/WWU-seminar-2018] Seminar today - and next week too!(#18)

We'll be working on Lab 5, a short one on data visualization.
Next week we'll be talking about fitting models to data, a critical tool in a scientist's arsenal!
(attn: @nataliegmoore @choudrs @ballanr @MeganMcAndie @karlaburch @erinleighh @amandarudolph @mscogs @ZacheryLaycock @frizzek @barberdegraaff @gibbslena @JMollerup)

**Comment by jradavenport** [comment]
A reminder: Data Science seminar today at 4pm! Lab 6 is now online and ready for your consideration!
